### PR TITLE
fix: global git credentials and some other stuff

### LINKED ISSUE #128: unable to clone private repos
We use a git credentials helper set on the project level - these credentials should be global so that the user can interact with their other private repos as well. 

reported by @TaoSunVoyage

### PR DESCRIPTION
**Pull request by rokroskar**
closes #128

### CODE REVIEW

**Comment by ableuler** [comment]
Given the name of the PR I thought I'd have to greenlight a `--global` flag somewhere, and suddenly I find myself trying to verify the entrypoint logic of our R images... This is false advertisement here 😂

**Comment by rokroskar** [comment]
Yeah I had to do that to not have the same git config copy-pasted in a few places... I thought it would just fly under the radar :)

**Comment by rokroskar** [comment]
To be fair, I tried to be honest about it and split it into two commits. So it could in principle be separated if you want.

**Comment by rokroskar** [comment]
Oh, this also closes #73 then...

**Comment by rokroskar** [comment]
I updated the title of the PR... 🥇

File: docker/py/entrypoint.sh [hunk 1]
```diff
@@ -24,11 +24,25 @@ find /tmp/renku-env -not -path '*.git*' -type f -print0 | xargs --null -I{} sh -
 
 if [[ -v CI_PROJECT ]];
 then
+    # set the global git credentials
```
Comment (ableuler) [inline docker/py/entrypoint.sh:27]: This relies on what's happening in the init container. Maybe create the actual credentials here (again) and place them directly in the users home directory (ie outside of the repo)? This would make it a bit nicer to re-use the image in a non-k8s setting, but at the cost of having the same credentials in two places... In principle the init container could even remove the local credentials again after successful clone to avoid this duplication.

**Review by ableuler — APPROVED** [review]
Looks good and works as it's supposed to. Left one comment for something that you could consider, but I'm fine with merging the PR as is.

File: docker/py/entrypoint.sh (hunk 1 above)
Comment (ableuler) [reply docker/py/entrypoint.sh:27]: Actually the best might be to check for local credentials here from the init container and remove them if they exist and then create the global ones.

Comment (rokroskar) [reply docker/py/entrypoint.sh:27]: I wanted to limit the places where we inject the oauth token into the environment. It would be easy for users to leak their oauth token if they e.g. copy-pasted their environment variables somewhere. They're more likely to look at their environment variables than their `.git/config` file, but I agree with you that it's not ideal the way it's implemented.

Comment (ableuler) [reply docker/py/entrypoint.sh:27]: Ok, my starting point was that I'd expect local config in the repo and global config in the users home directory, but I see your point: it's true that the environment variable of the init-container are less exposed than those of the main container. So let's merge this.
